python moravec.py cats_1.png  
python moravec.py harrypotter_2.png  
python moravec.py news_2.png
python moravec.py cats_2.png        
python moravec.py hitler_1.png     
python moravec.py terminator_1.png
python moravec.py 007_1.png   
python moravec.py commercial_1.png   
python moravec.py hitler_2.png  
python moravec.py terminator_2.png
python moravec.py commercial_2.png  
python moravec.py matrix_1.png
python moravec.py  matrix_2.png
python moravec.py 007_2.png 
python moravec.py harrypotter_1.png  
python moravec.py news_1.png
